name: AwakeBar
options:
  minimumXcodeGenVersion: 2.44.1
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 6.0
targets:
  AwakeBar:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: AwakeBar
    resources:
      - path: AwakeBar/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dshakiba.AwakeBar
        PRODUCT_NAME: AwakeBar
        INFOPLIST_FILE: AwakeBar/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets:
        - AwakeBarTests
  AwakeBarTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: AwakeBarTests
    dependencies:
      - target: AwakeBar
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AwakeBar.app/Contents/MacOS/AwakeBar"
        BUNDLE_LOADER: "$(TEST_HOST)"
        PRODUCT_BUNDLE_IDENTIFIER: com.dshakiba.AwakeBarTests
